language: node_js
node_js:
    - "6"
    - "5"
    - "4"
    - "node"
env:
    - dbuser=enterhere
    - password=enterhere
    - adminpassword=enterhere
script: npm run gulp


# Install apt addons
# before_install
# install
# before_script
# script
# after_success
# after_failure
# OPTIONAL before_deploy
# OPTIONAL deploy
# OPTIONAL after_deploy
# after_script