language: node_js
node_js:
    - "7"
    - "6"
    - "node"
install: npm install
before_script: npm run build
script: npm run app

# Install apt addons
# before_install
# install
# before_script
# script
# after_success
# after_failure
# OPTIONAL before_deploy
# OPTIONAL deploy
# OPTIONAL after_deploy
# after_script
